//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionMap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataAlbionMapEntities : DbContext
    {
        public DataAlbionMapEntities()
            : base("name=DataAlbionMapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MainLocation> MainLocations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfFiber> TypeOfFibers { get; set; }
        public virtual DbSet<TypeOfHide> TypeOfHides { get; set; }
        public virtual DbSet<TypeOfLocation> TypeOfLocations { get; set; }
        public virtual DbSet<TypeOfOre> TypeOfOres { get; set; }
        public virtual DbSet<TypeOfRegion> TypeOfRegions { get; set; }
        public virtual DbSet<TypeOfStone> TypeOfStones { get; set; }
        public virtual DbSet<TypeOfWood> TypeOfWoods { get; set; }
    }
}
