//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationAndResource
    {
        public int ID { get; set; }
        public int IDMainLocation { get; set; }
        public int IDTypeOfLocation { get; set; }
    
        public virtual MainLocation MainLocation { get; set; }
        public virtual TypeOfLocation TypeOfLocation { get; set; }
    }
}
