//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeOfLocation()
        {
            this.MainLocations = new HashSet<MainLocation>();
        }
    
        public int ID { get; set; }
        public string NameLocation { get; set; }
        public Nullable<int> IfWood { get; set; }
        public Nullable<int> IfStone { get; set; }
        public Nullable<int> IfHide { get; set; }
        public Nullable<int> IfFiber { get; set; }
        public Nullable<int> IfOre { get; set; }
    
        public virtual TypeOfFiber TypeOfFiber { get; set; }
        public virtual TypeOfHide TypeOfHide { get; set; }
        public virtual TypeOfOre TypeOfOre { get; set; }
        public virtual TypeOfStone TypeOfStone { get; set; }
        public virtual TypeOfWood TypeOfWood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainLocation> MainLocations { get; set; }
    }
}
